// editor/src/panels/build_manager.cpp
// ─────────────────────────────────────────────────────────────
// Build & Export Manager — standalone implementation.
// ─────────────────────────────────────────────────────────────

#include "build_manager.h"
#include "ai_chat.h"

#include <imgui.h>
#include <SDL2/SDL.h>

#include <sys/stat.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <algorithm>

namespace beigebox {

BuildManager::BuildManager()
{
    ClearLog();
}

void BuildManager::Log(const std::string& msg)
{
    buildLog_.push_back(msg);
    if (aiChat_) aiChat_->AppendMessage("system", "[Build] " + msg);
    SDL_Log("[Build] %s", msg.c_str());
}

void BuildManager::ClearLog()
{
    buildLog_.clear();
    buildLog_.push_back("Build Manager ready.");
}

bool BuildManager::CopyFile(const std::string& src, const std::string& dst)
{
    std::ifstream in(src, std::ios::binary);
    if (!in.good()) return false;
    std::ofstream out(dst, std::ios::binary);
    if (!out.good()) return false;
    out << in.rdbuf();
    return true;
}

bool BuildManager::CopyDir(const std::string& srcDir, const std::string& dstDir)
{
    std::string cmd = "cp -r \"" + srcDir + "\"/* \"" + dstDir + "\"/ 2>/dev/null";
    return system(cmd.c_str()) == 0;
}

std::string BuildManager::GenerateLaunchScript() const
{
    std::string script = "#!/bin/sh\n";
    script += "# M.A.D. Runtime Launcher — v" + std::string(versionBuf_) + "\n";
    script += "# Generated by M.A.D. Editor Build Manager\n\n";
    script += "cd \"$(dirname \"$0\")\"\n";
    script += "export LD_LIBRARY_PATH=\"./lib:$LD_LIBRARY_PATH\"\n";
    script += "exec ./beigebox_runtime \"$@\"\n";
    return script;
}

bool BuildManager::ValidateBuild()
{
    // Check that the runtime executable exists
    std::string exePath = rootPath_ + "/build/engine/beigebox_runtime";
    std::ifstream test(exePath);
    if (!test.good())
    {
        Log("ERROR: Runtime not found at " + exePath);
        Log("  Build the project first: cmake --build build");
        return false;
    }
    return true;
}

// ═════════════════════════════════════════════════════════════
// Main Draw
// ═════════════════════════════════════════════════════════════

void BuildManager::Draw()
{
    if (!show_) return;

    ImGui::SetNextWindowSize(ImVec2(520, 500), ImGuiCond_FirstUseEver);
    ImGui::Begin("Build & Export Manager", &show_);

    // ── Configuration ────────────────────────────────────────
    if (ImGui::CollapsingHeader("Configuration", ImGuiTreeNodeFlags_DefaultOpen))
    {
        ImGui::InputText("Output Path", outputPath_, sizeof(outputPath_));
        ImGui::SameLine();
        if (ImGui::Button("...##browseOutput", ImVec2(30, 0)))
        {
#ifdef __linux__
            FILE* pipe = popen("zenity --file-selection --directory 2>/dev/null", "r");
            if (pipe) {
                char line[512];
                if (fgets(line, sizeof(line), pipe)) {
                    size_t len = strlen(line);
                    if (len > 0 && line[len-1] == '\n') line[len-1] = '\0';
                    strncpy(outputPath_, line, sizeof(outputPath_) - 1);
                }
                pclose(pipe);
            }
#endif
        }

        ImGui::InputText("Version", versionBuf_, sizeof(versionBuf_));

        ImGui::Checkbox("Linux (native)", &buildLinux_);
        ImGui::SameLine();
        ImGui::Checkbox("Windows (cross)", &buildWindows_);
        ImGui::SameLine();
        ImGui::Checkbox("Package .tar.gz", &packageTarGz_);

        ImGui::Separator();
        ImGui::Text("Package contents:");
        ImGui::BulletText("beigebox_runtime");
        ImGui::BulletText("assets/ (sprites, sounds, music, scripts)");
        ImGui::BulletText("data/ (units, buildings, factions)");
        ImGui::BulletText("scenarios/");
        ImGui::BulletText("ui/menus/");
        ImGui::BulletText("launch.sh");
        ImGui::BulletText("VERSION");
    }

    ImGui::Separator();

    // ── Build button ─────────────────────────────────────────
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(16, 12));
    if (ImGui::Button("Build & Export", ImVec2(200, 0)))
        DoBuild();
    ImGui::PopStyleVar();

    ImGui::SameLine();
    if (ImGui::Button("Clear Log"))
        ClearLog();

    ImGui::SameLine();
    ImGui::Checkbox("Auto-scroll", &autoScroll_);

    // ── Progress ─────────────────────────────────────────────
    if (buildRunning_)
    {
        ImGui::ProgressBar(buildProgress_, ImVec2(0, 20));
        ImGui::SameLine();
        ImGui::Text("%.0f%%", buildProgress_ * 100.0f);
        ImGui::Text("%s", buildStatus_.c_str());
    }

    ImGui::Separator();

    // ── Build log ────────────────────────────────────────────
    ImGui::BeginChild("##buildLog", ImVec2(0, 0), true);

    for (auto& entry : buildLog_)
    {
        ImVec4 col(0.7f, 0.7f, 0.7f, 1.0f);
        if (entry.find("ERROR") != std::string::npos)
            col = ImVec4(1.0f, 0.3f, 0.3f, 1.0f);
        else if (entry.find("DONE") != std::string::npos ||
                 entry.find("Complete") != std::string::npos)
            col = ImVec4(0.3f, 0.9f, 0.3f, 1.0f);
        else if (entry.find("  ") == 0) // indented = detail
            col = ImVec4(0.5f, 0.5f, 0.5f, 1.0f);

        ImGui::TextColored(col, "%s", entry.c_str());
    }

    if (autoScroll_ && ImGui::GetScrollY() >= ImGui::GetScrollMaxY())
        ImGui::SetScrollHereY(1.0f);

    ImGui::EndChild();

    ImGui::End();
}

// ═════════════════════════════════════════════════════════════
// Build Pipeline
// ═════════════════════════════════════════════════════════════

void BuildManager::DoBuild()
{
    if (buildRunning_) return;

    if (!ValidateBuild())
    {
        buildProgress_ = 0.0f;
        buildStatus_ = "Build failed — see log";
        return;
    }

    buildRunning_ = true;
    buildProgress_ = 0.0f;
    currentStep_ = 0;
    ClearLog();
    Log("Starting build v" + std::string(versionBuf_) + "...");

    std::string dest(outputPath_);

    // Step 1: Clean output directory
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Cleaning output directory...";
    Log("  [1/" + std::to_string(totalSteps_) + "] Cleaning " + dest + "...");
    std::string rmCmd = "rm -rf \"" + dest + "\" && mkdir -p \"" + dest + "\"";
    system(rmCmd.c_str());

    // Step 2: Create subdirectories
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Creating directory structure...";
    Log("  [2/" + std::to_string(totalSteps_) + "] Creating subdirectories...");
    const char* subdirs[] = {"assets", "assets/sprites", "assets/sounds",
        "assets/music", "assets/scripts", "data", "data/units",
        "data/buildings", "data/heroes", "data/factions",
        "scenarios", "ui", "ui/menus"};
    for (auto& sd : subdirs)
    {
        std::string full = dest + "/" + sd;
        mkdir(full.c_str(), 0755);
    }

    // Step 3: Copy runtime
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Copying runtime executable...";
    Log("  [3/" + std::to_string(totalSteps_) + "] Copying runtime...");
    std::string srcExe = rootPath_ + "/build/engine/beigebox_runtime";
    std::string dstExe = dest + "/beigebox_runtime";
    if (CopyFile(srcExe, dstExe))
    {
        chmod(dstExe.c_str(), 0755);
        Log("    beigebox_runtime ✓");
    }
    else
        Log("    ERROR: Failed to copy runtime");

    // Step 4: Copy assets
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Copying assets...";
    Log("  [4/" + std::to_string(totalSteps_) + "] Copying assets...");
    auto copyAssetDir = [&](const char* sub) {
        std::string src = rootPath_ + "/" + sub;
        std::string dst = dest + "/" + sub;
        CopyDir(src, dst);
        Log("    " + std::string(sub) + " ✓");
    };
    copyAssetDir("assets/sprites");
    copyAssetDir("assets/sounds");
    copyAssetDir("assets/music");
    copyAssetDir("assets/scripts");

    // Step 5: Copy data
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Copying game data...";
    Log("  [5/" + std::to_string(totalSteps_) + "] Copying game data...");
    copyAssetDir("data/units");
    copyAssetDir("data/buildings");
    copyAssetDir("data/heroes");
    copyAssetDir("data/factions");

    // Step 6: Copy scenarios & UI
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Copying scenarios and UI...";
    Log("  [6/" + std::to_string(totalSteps_) + "] Copying scenarios & UI...");
    copyAssetDir("scenarios");
    copyAssetDir("ui/menus");

    // Step 7: Generate launcher + version
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Generating launcher...";
    Log("  [7/" + std::to_string(totalSteps_) + "] Generating launch.sh...");
    std::string script = GenerateLaunchScript();
    std::string lp = dest + "/launch.sh";
    std::ofstream lf(lp);
    lf << script; lf.close();
    chmod(lp.c_str(), 0755);
    Log("    launch.sh ✓");

    std::string vp = dest + "/VERSION";
    std::ofstream vf(vp);
    vf << versionBuf_ << "\n"; vf.close();
    Log("    VERSION ✓");

    // Step 8: Package .tar.gz
    currentStep_++;
    buildProgress_ = static_cast<float>(currentStep_) / totalSteps_;
    buildStatus_ = "Packaging...";
    Log("  [8/" + std::to_string(totalSteps_) + "] Packaging...");

    if (packageTarGz_)
    {
        std::string tgzName = std::string(outputPath_) + ".tar.gz";
        std::string tarCmd = "cd \"" + std::string(outputPath_) +
            "\"/.. && tar czf \"" + tgzName + "\" \"$(basename \"" +
            std::string(outputPath_) + "\")\"";
        if (system(tarCmd.c_str()) == 0)
            Log("    " + tgzName + " ✓");
        else
            Log("    ERROR: Failed to create .tar.gz (tar not found?)");
    }
    else
    {
        Log("    Skipped (.tar.gz disabled)");
    }

    buildProgress_ = 1.0f;
    buildStatus_ = "DONE";
    Log("Build complete: " + dest);
    Log("  Run with: cd " + dest + " && ./launch.sh");
    buildRunning_ = false;
}

void BuildManager::DoPackage()
{
    // Manual re-package of existing build
    if (packageTarGz_)
    {
        std::string tgzName = std::string(outputPath_) + ".tar.gz";
        std::string tarCmd = "cd \"" + std::string(outputPath_) +
            "\"/.. && tar czf \"" + tgzName + "\" \"$(basename \"" +
            std::string(outputPath_) + "\")\"";
        if (system(tarCmd.c_str()) == 0)
            Log("Packaged: " + tgzName);
        else
            Log("ERROR: Failed to create .tar.gz");
    }
}

} // namespace beigebox
